export const FEEDBACK_INCORRECT_TIME = 1500;
export const FEEDBACK_CORRECT_TIME = 2500;
export const FEEDBACK_TIME = FEEDBACK_CORRECT_TIME + FEEDBACK_INCORRECT_TIME;
export const FEEDBACK_FALLBACK = 1000;
export const FEEDBACK_SERVER_FALLBACK = 200;

export const DEFAULT_WAITING_TIME_FOR_START_GAME_SEK = 10;