import { IUser } from "../../types/user";

export const UserActionTypes = {
    CHECK_EMAIL_FAILURE: "CHECK_EMAIL_FAILURE",
    CHECK_EMAIL_START: "CHECK_EMAIL_START",
    CHECK_EMAIL_SUCCESS: "CHECK_EMAIL_SUCCESS",
    CHECK_USER_SESSION: "CHECK_USER_SESSION",
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
    SIGN_OUT_START: "SIGN_OUT_START",
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
    SIGN_UP_START: "SIGN_UP_START",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    USER_EDIT_START: "USER_EDIT_START",
    USER_EDIT_SUCCESS: "USER_EDIT_SUCCESS",
    USER_EDIT_FAILURE: "USER_EDIT_FAILURE",
    USER_ERROR_CLEAR: "USER_ERROR_CLEAR",
    VERIFY_CODE_START: "VERIFY_CODE_START",
    VERIFY_CODE_SUCCESS: "VERIFY_CODE_SUCCESS",
    VERIFY_CODE_FAILURE: "VERIFY_CODE_FAILURE",
};

export interface IUserState {
    currentUser: IUser;
    isFetching: boolean;
    signInEmail: string;
    userError: string;
}